# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title pagerank using Rcpp
#' @description pagerank using Rcpp
#' @param adj_matrix adjacency matrix
#' @param alpha Correction probability of transition probability matrix
#' @param max_iter Maximum Number Of Iterations
#' @return Pagerank values for each node
#' @examples
#' \dontrun{
#' r <- pagerankc(adj_matrix, alpha=0.9, max_iter=5000)
#' }
#' @export
pagerankc <- function(adj_matrix, alpha = 0.85, max_iter = 10000L) {
    .Call('_SA23229026_pagerankc', PACKAGE = 'SA23229026', adj_matrix, alpha, max_iter)
}

